### ISSUE TITLE
Error 40261: Invalid Device ID

### ISSUE THREAD

**Issue by flk652** [alessiolombardo/FoxESSMonitor#1]
When trying to extract or export data, I'm always receiving:
Error 40261: Invalid Device ID
I'm using the device ID provided by foxesscloud, inverter details, inverter SN.
Is that the expected ID or have I to use another one and which one (where to find) should I use.

Thanks in advance.

**Comment by alessiolombardo** [comment]
The Device/Inverter ID is not the Device/Inverter SN.
The Device/Inverter ID has this pattern: "ffffffff-ffff-ffff-ffff-ffffffffffff" (UUID format)
Look this document to find it: [https://github.com/macxq/foxess-ha/blob/main/README.md#auxiliary-notes](https://github.com/macxq/foxess-ha/blob/main/README.md#auxiliary-notes)
