### ISSUE TITLE
Error: Request data error

### ISSUE THREAD

**Issue by flk652** [alessiolombardo/FoxESSMonitor#2]
For one day data extract and data export has performed properly.

Since yesterday, 20.02.2024, each attempt to request data from fox-cloud will be aborted by following error message:
Request data error
During the same time, when foxess_monitor is not performing well, I'll be able to access fox-cloud using firefox or chrome.
Is there any log or debug available to get details about the reason why data request has failed?

Thanks in advance-
![foxmon_error](https://github.com/alessiolombardo/FoxESSMonitor/assets/37533505/6e807369-b242-4820-9697-f8adc94abf92)

**Comment by alessiolombardo** [comment]
Foxcloud has turned off the old APIs. New Open APIs are now available (https://www.foxesscloud.com/public/i18n/en/OpenApiDocument.html) and I will update the code as soon as possible.

**Comment by alessiolombardo** [comment]
New version released (v. 2.0).
